[tool.poetry]
name = "asnd"
version = "0.1.0"
description = ""
authors = ["l3v1k"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
maxminddb = "^2.5.1"
tabulate = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
